# -*- coding: utf-8 -*-
"""analisis_teks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JZrTBwv7680NO4Vqw1zOy1GwWPp-2Ys3
"""

# Program menghitung jumlah kata dan kalimat dari sebuah teks

def hitung_teks(teks):
    if not teks.strip():
        return 0, 0
    jumlah_kata = len(teks.split())
    jumlah_kalimat = teks.count(".")
    return jumlah_kata, jumlah_kalimat

teks = "Media sosial atau disebut juga dengan jejaring sosial, seperti Facebook, Twitter, Instagram, dan masih banyak lagi ternyata tidak hanya digunakan sebagai tempat berkumpul atau berbagi di dunia maya. Namun, media sosial kini juga bisa dimanfaatkan sebagai media untuk mengembangkan sebuah bisnis. Saat ini telah banyak para pengusaha yang beralih ke media sosial dalam memasarkan produk mereka baik barang ataupun jasa. Beralihnya para pelaku bisnis ke media ini dikarenakan jejaring sosial memiliki manfaat yang sangat banyak bagi usaha bisnis. Berikut ini adalah alasan mengapa jejaring sosial bisa menjadi alat promosi yang paling efektif."

jumlah_kata, jumlah_kalimat = hitung_teks(teks)

print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")

# Program menghitung jumlah kata dan kalimat dari sebuah teks

def hitung_teks(teks):
    if not teks.strip():
        return 0, 0
    jumlah_kata = len(teks.split())
    jumlah_kalimat = teks.count(".")
    return jumlah_kata, jumlah_kalimat

teks = "Belajar pemrograman itu menyenangkan."

jumlah_kata, jumlah_kalimat = hitung_teks(teks)

print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")

# Program menghitung jumlah kata dan kalimat dari sebuah teks

def hitung_teks(teks):
    if not teks.strip():
        return 0, 0
    jumlah_kata = len(teks.split())
    jumlah_kalimat = teks.count(".")
    return jumlah_kata, jumlah_kalimat

teks = ""

jumlah_kata, jumlah_kalimat = hitung_teks(teks)

print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")
