# -*- coding: utf-8 -*-
"""02_string_kalimat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZuuDvdV5SB42UEstbEVkB8xgBLypoP_W
"""

# 02_string_kalimat.py
# Membuat objek string dengan karakter khusus

# K1: apostrof di dalam string → gunakan kutip ganda sebagai pembungkus
K1 = "Saya tak 'kan menyerah."

# K2: kutip ganda di dalam string → gunakan kutip tunggal sebagai pembungkus
K2 = 'Ia berkata, "Aku menyayangimu."'

# K3: kutip ganda di awal/akhir DAN apostrof di dalam → gunakan triple-quote
K3 = '''"Coba jelaskan pengertian 'cross-validation' dalam Machine Learning!"'''

# K4: tanda titik di tengah nomor surat (bukan akhir kalimat) → string biasa
K4 = "Surat keputusan itu bernomor 62/UN.34/19/2023."

print(K1)
print(K2)
print(K3)
print(K4)