# -*- coding: utf-8 -*-
"""03_akar_kuadrat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gTKj4OtCK23bwyTNjstOkSmSIZHkGB2n
"""

# 03_akar_kuadrat.py
# Menghitung akar-akar persamaan kuadrat ax^2 + bx + c = 0

import math

def hitung_akar(a, b, c):
    if a == 0:
        return "Error: nilai a tidak boleh nol."
    diskriminan = b**2 - 4*a*c
    if diskriminan > 0:
        x1 = (-b + math.sqrt(diskriminan)) / (2*a)
        x2 = (-b - math.sqrt(diskriminan)) / (2*a)
        return f"Dua akar real berbeda:\n  x1 = {x1:.3f}\n  x2 = {x2:.3f}"
    elif diskriminan == 0:
        x = -b / (2*a)
        return f"Akar kembar:\n  x1 = x2 = {x:.3f}"
    else:
        return "Persamaan ini hanya memiliki akar-akar imajiner."

print(hitung_akar(1,-5,6))
print(hitung_akar(1,-4,4))
print(hitung_akar(1,2,5))
print(hitung_akar(0,3,2))
