# -*- coding: utf-8 -*-
"""06_interval_proporsi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1laEj4U2Hu-dgBJ8z80BkWfpWmrmIwLn7
"""

# 06_interval_proporsi.py
# Menghitung interval konfidensi untuk proporsi populasi

import math

def tentukan_z(alpha):
    if alpha == 5:
        return 1.96
    elif alpha == 10:
        return 1.645
    else:
        return None

def hitung_interval(p_hat, n, alpha):
    if p_hat < 0 or p_hat > 1:
        return "Error: proporsi harus bernilai antara 0 dan 1."
    z = tentukan_z(alpha)
    if z is None:
        return "Error: alpha hanya boleh 5 atau 10."
    margin = z * math.sqrt(p_hat * (1 - p_hat) / n)
    bawah  = p_hat - margin
    atas   = p_hat + margin
    return (bawah, atas, alpha, z)

p_hat = float(input("Masukkan proporsi sampel (p̂): "))
n     = int(input("Masukkan ukuran sampel (n): "))
alpha = int(input("Masukkan alpha (5 atau 10): "))

hasil = hitung_interval(p_hat, n, alpha)

if isinstance(hasil, str):
    print(hasil)
else:
    bawah, atas, a, z = hasil
    print(f"\nInterval konfidensi {100-a}% (z = {z}):")
    print(f"  {bawah:.4f} < p < {atas:.4f}")

# 06_interval_proporsi.py
# Menghitung interval konfidensi untuk proporsi populasi

import math

def tentukan_z(alpha):
    if alpha == 5:
        return 1.96
    elif alpha == 10:
        return 1.645
    else:
        return None

def hitung_interval(p_hat, n, alpha):
    if p_hat < 0 or p_hat > 1:
        return "Error: proporsi harus bernilai antara 0 dan 1."
    z = tentukan_z(alpha)
    if z is None:
        return "Error: alpha hanya boleh 5 atau 10."
    margin = z * math.sqrt(p_hat * (1 - p_hat) / n)
    bawah  = p_hat - margin
    atas   = p_hat + margin
    return (bawah, atas, alpha, z)

p_hat = float(input("Masukkan proporsi sampel (p̂): "))
n     = int(input("Masukkan ukuran sampel (n): "))
alpha = int(input("Masukkan alpha (5 atau 10): "))

hasil = hitung_interval(p_hat, n, alpha)

if isinstance(hasil, str):
    print(hasil)
else:
    bawah, atas, a, z = hasil
    print(f"\nInterval konfidensi {100-a}% (z = {z}):")
    print(f"  {bawah:.4f} < p < {atas:.4f}")

# 06_interval_proporsi.py
# Menghitung interval konfidensi untuk proporsi populasi

import math

def tentukan_z(alpha):
    if alpha == 5:
        return 1.96
    elif alpha == 10:
        return 1.645
    else:
        return None

def hitung_interval(p_hat, n, alpha):
    if p_hat < 0 or p_hat > 1:
        return "Error: proporsi harus bernilai antara 0 dan 1."
    z = tentukan_z(alpha)
    if z is None:
        return "Error: alpha hanya boleh 5 atau 10."
    margin = z * math.sqrt(p_hat * (1 - p_hat) / n)
    bawah  = p_hat - margin
    atas   = p_hat + margin
    return (bawah, atas, alpha, z)

p_hat = float(input("Masukkan proporsi sampel (p̂): "))
n     = int(input("Masukkan ukuran sampel (n): "))
alpha = int(input("Masukkan alpha (5 atau 10): "))

hasil = hitung_interval(p_hat, n, alpha)

if isinstance(hasil, str):
    print(hasil)
else:
    bawah, atas, a, z = hasil
    print(f"\nInterval konfidensi {100-a}% (z = {z}):")
    print(f"  {bawah:.4f} < p < {atas:.4f}")